name: 🔨Build Android APK

on:
  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.29.1"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Setup Keystore
        shell: bash
        run: |
          echo ${{ secrets.BASE64_KEYSTORE }} | base64 --decode > android/app/keystore.jks

      - name: Build APK
        run: |
          flutter build apk --release --split-per-abi \
            --dart-define=STORE_PASSWORD=${{ secrets.STORE_PASSWORD }} \
            --dart-define=KEY_PASSWORD=${{ secrets.KEY_PASSWORD }} \
            --dart-define=KEY_ALIAS=${{ secrets.KEY_ALIAS }}

      - uses: actions/upload-artifact@v4
        with:
          name: release-apks
          path: build/**/outputs/apk/release/*.apk